# netlify.toml
[build]
  publish = "dist"
  command = "npm run build && cd netlify/functions && npm install"

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200